services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - DJANGO_ENV=development
        environment:
            - SENTENCE_TRANSFORMERS_HOME=/app/.cache/
            - TRANSFORMERS_CACHE=/app/.cache/
            - HF_HOME=/app/.cache/
            - TRANSFORMERS_CACHE=/app/.cache/
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - './:/app'
        restart: always
